name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Decode Secrets
        env :
          COMBINED_SERVER_SECRETS: ${{secrets.COMBINED_SERVER_SECRETS}}
        run: echo $COMBINED_SERVER_SECRETS | base64 -d > server/.env
          
          
      - run: |
          pwd
          cd client
          pwd
          ls
          yarn install
          CI=false yarn run build
          cd ..
          cd server
          yarn install

          
          
          




  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      # - run: rm -rf server/
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Decode Secrets
        env :
          COMBINED_SERVER_SECRETS: ${{secrets.COMBINED_SERVER_SECRETS}}
        run: echo $COMBINED_SERVER_SECRETS | base64 -d > server/.env
          
      - run: |
          pwd
          cd client
          pwd
          ls
          yarn install
          CI=false yarn run build
          cd ..
          cd server
          yarn install
          pwd
          pm2 restart 0
          pm2 save
          sudo service nginx restart
          

